### PR TITLE
Roadworks visible on the map

### LINKED ISSUE #84: Roadworks – tagged in OSM – visible on the map
As a way to improve both the standard solution and any embedded maps in news on web scenarios, we should be able to show roads that are closed. To the be able to inform cyclists and route them around. Icon: No entry sign. (See mockup under.)

Need help on this, but my suggestion: 

1. construction=* and highway=construction and (construction<>motorway or bicycle=no) - Tested here: http://overpass-turbo.eu/s/1AG0
2. check_date=[has a date] – To avoid cases that are old and not correctly updated?

We avoid construction areas. This is too complex in my book. Correct me if I am wrong. 

266586943-8ee4c23c-d472-4a07-9e2c-fd525b20f3d7

### PR DESCRIPTION
**Pull request by Beck-berry**
image

Closes [cycling-norway#84](https://github.com/buskerudbyen/cycling-norway/issues/84)

### CODE REVIEW

**Comment by tsobuskerudbyen** [comment]
Seems to be some rail lines with the icon as well (https://www.openstreetmap.org/way/601739911)? The three to the right in the screenshot. Or? That is not needed.

**Comment by leonardehrenfried** [comment]
@tsobuskerudbyen Is it expected that there are lots of these icons? I would have thought that there are a lot fewer.

**Comment by tsobuskerudbyen** [comment]
This area (from screenshot and my OSM-link over) is a huge construction site, because of both a new bridge over the river and a new train station at the same time. There where (and will be after it is finished) a lot of cycle paths around the area, with different sections because of differences in role and surfaces. 

What can be done on this related to programming? Can closeness/connected roads be a factor and then lump more of the icons together? Yes, please, if possible and viable with not too much work.

@Beck-berry  found a good area to test this in the area from the screenshot.  :) More: 

-  Another one is a closed bridge, because part of it is removed because of a collision - https://www.openstreetmap.org/way/112396089. This should be clearly visible. 
- And another constriction site with planned cycle infrastructure, that should not be visible because of different tagging is here: https://www.openstreetmap.org/way/1022237779 ).

**Comment by Beck-berry** [comment]
You were right, the railways were marked accidentally. I fixed that.

Also, on higher zoom levels, there are "more" icons, each road has its own. But smaller zoom levels look ok. Their first appearance is from 12, let me know, if it could be even higher.

Zoom level 15:
image
Zoom level 19:
image

I'm still unsure why those roads are not visible but we have this construction mark on them. Should we make the rule stricter somehow?

**Comment by tsobuskerudbyen** [comment]
@leonardehrenfried : Anything that is needed from your side on this now?

**Comment by leonardehrenfried** [comment]
Sorry, I overlooked this one. I will deploy it now.

**Review by leonardehrenfried — APPROVED** [review]

**Pull request merged**
